### PR TITLE
Added purescript-functions dependency

### PR DESCRIPTION
**Pull request by FrigoEU**
Tiny change, just adding this dependency since Fnx is no longer imported automatically.

### CODE REVIEW

**Comment by joneshf** [comment]
I'd like to merge this, but I don't want to depend on a release candidate. Is there any difference between the rc and the same version? I can change it before release, not asking you to do more work. I'm just unclear on what's different if anything.

**Comment by FrigoEU** [comment]
Hey,

Sorry for the late reply, lost sight of this. Seems the only difference between 0.1.0 and 0.1.0-rc.1 is some lest strict dependencies. Either one are fine for this package, pick the one you like best :).

**Comment by joneshf** [comment]
Gotcha. Thanks!

**Comment by joneshf** [comment]
If it's not too much of a bother, I'm going to hold off for a day to release a new version of these three. There's a bit of stuff that needs to change, and I don't have the time for it tonight.

**Pull request merged**
